apiVersion: v1
kind: Service
metadata:
  name: drippy-api-service
  namespace: drippy-api
  labels:
    app: drippy-api
spec:
  selector:
    app: drippy-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
