apiVersion: apps/v1
kind: Deployment
metadata:
  name: drippy-api
  namespace: drippy-api
  labels:
    app: drippy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drippy-api
  template:
    metadata:
      labels:
        app: drippy-api
    spec:
      containers:
        - name: drippy-api
          image: 290738313620.dkr.ecr.us-east-1.amazonaws.com/drippy-api-eks:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_URL
              value: https://www.google.com
