apiVersion: apps/v1
kind: Deployment
metadata:
  name: drippy-api
  namespace: drippy-api
  labels:
    app: drippy-api
spec:
  replicas: 2
  # revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: drippy-api
  template:
    metadata:
      labels:
        app: drippy-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: drippy-api-eks
          image: 290738313620.dkr.ecr.us-east-1.amazonaws.com/drippy-api-eks:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_URL
              value: https://upstream.tackle.io
