apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
namespace: drippy-api
images:
  - name: 290738313620.dkr.ecr.us-east-1.amazonaws.com/drippy-api-eks
    newTag: b15932e6d639940c1bcb0aaacd06e0e0b038d55b
