apiVersion: v1
kind: Service
metadata:
  name: drippy-api
  namespace: drippy-api
  labels:
    app: drippy-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: drippy-api
