apiVersion: v1
kind: Service
metadata:
  name: drippy-api
  namespace: drippy-api
  labels:
    app: drippy-api
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # service.beta.kubernetes.io/aws-load-balancer-internal: "false" or "true" if private
spec:
  selector:
    app: drippy-api
  type: LoadBalancer
  ports:
    - port: 80
      # port: 8080
      protocol: TCP
      targetPort: 8080
