apiVersion: v1
kind: Service
metadata:
  name: drippy-api-eks
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: drippy-api-eks
    
# saved

apiVersion: v1
kind: Service
metadata:
  name: drippy-api
  namespace: drippy-api
  labels:
    app: drippy-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      # protocol: TCP
  selector:
    app: drippy-api