apiVersion: v1
kind: Service
metadata:
  name: drippy-api-eks
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: drippy-api-eks

# delete LoadBalancer