apiVersion: apps/v1
kind: Deployment
metadata:
  name: drippy-api
spec:
  selector:
    matchLabels:
      app: drippy-api
  replicas: 2
  template:
    metadata:
      labels:
        app: drippy-api
    spec:
      containers:
        - name: drippy-api
          image: 290738313620.dkr.ecr.us-east-1.amazonaws.com/drippy-api-eks:latest
          ports:
            - containerPort: 8000
# spec:
#  containers:
#  - name: your-app-container
#    image: <YOUR_ECR_REPO_URL>/your-app:latest
